# Generated by Django 4.2.1 on 2024-03-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_category_recipes_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.category'),
        ),
    ]
